pipeline{
    agent{
        label "Cart-Ci"
    }

    environment {
        APP_VERSION = "1.0"
        SSH = credentials('SSH-CENTOS')
    }

    stages{
        stage("Stage 1"){
            environment {
                APP_VERSION = "2.0"
            }
            steps{
                sh 'env'
            }
        }
    }
}          